version: '3'

services:
  api-bookhub:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: bookhub-admin
    ports:
      - 3006:3006
    volumes:
      - ./:/home/bookhub_api_admin/app
    tty: true
    networks:
      - bookhub-network

  db:
    image: mongo:4.4
    container_name: mongo-db
    volumes:
      - /mongodb/dbdata:/data/db
      - /mongodb/configdb:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: bookhub-admin
    networks:
      - bookhub-network

networks:
  bookhub-network:
    driver: bridge
